### ISSUE TITLE
[LIVE - ROYAL ALEXANDRA] Crash loading all patient data for dashboard

### ISSUE THREAD

**Issue by mbarton** [rcpch/national-paediatric-diabetes-audit#785]
```
Internal Server Error: /all_patient_charts

KeyError at /all_patient_charts
nan

Request Method: GET
Request URL: http://npda.rcpch.ac.uk/all_patient_charts
```

**Comment by eatyourpeas** [comment]
fixed in #787

**Comment by mbarton** [comment]
@eatyourpeas could you have another look? I'm still seeing the crash on the Royal Alexandra dashboard

**Comment by mbarton** [comment]
This is also happening for Royal Preston ~~and UCL~~ (it's not happening for UCL, my mistake). I think it's because there are some patients missing IMD values
